//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFProjektv1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFProjektv1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string MainWaindow_Label_PleaseWait {
            get {
                return ResourceManager.GetString("MainWaindow.Label_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainWindow_Btton_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Btton_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string MainWindow_Closing {
            get {
                return ResourceManager.GetString("MainWindow.Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oponent.
        /// </summary>
        public static string MainWindow_Label_AwayTeam {
            get {
                return ResourceManager.GetString("MainWindow.Label_AwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen Team.
        /// </summary>
        public static string MainWindow_Label_HomeTeam {
            get {
                return ResourceManager.GetString("MainWindow.Label_HomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the teams and press the ball.
        /// </summary>
        public static string MainWindow_Label_PleaseWat_Loaded {
            get {
                return ResourceManager.GetString("MainWindow.Label_PleaseWat_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to chose both teams.
        /// </summary>
        public static string MainWindow_TeamsNotChosenMessage {
            get {
                return ResourceManager.GetString("MainWindow.TeamsNotChosenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWAY TEAM.
        /// </summary>
        public static string MatchWindow_LabelAwayTeam {
            get {
                return ResourceManager.GetString("MatchWindow_LabelAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played games:.
        /// </summary>
        public static string MatchWindow_LabelAwayTeamNumberOfMatches {
            get {
                return ResourceManager.GetString("MatchWindow_LabelAwayTeamNumberOfMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal difference:.
        /// </summary>
        public static string MatchWindow_LabelGoalDifference {
            get {
                return ResourceManager.GetString("MatchWindow_LabelGoalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals received:.
        /// </summary>
        public static string MatchWindow_LabelGoalsReceived {
            get {
                return ResourceManager.GetString("MatchWindow_LabelGoalsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored:.
        /// </summary>
        public static string MatchWindow_LabelGoalsScored {
            get {
                return ResourceManager.GetString("MatchWindow_LabelGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME TEAM.
        /// </summary>
        public static string MatchWindow_LabelHomeTeam {
            get {
                return ResourceManager.GetString("MatchWindow_LabelHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal diference:.
        /// </summary>
        public static string MatchWindow_LabelHomeTeamGoalDifference {
            get {
                return ResourceManager.GetString("MatchWindow_LabelHomeTeamGoalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played games:.
        /// </summary>
        public static string MatchWindow_LabelHomeTeamNumberOfMatches {
            get {
                return ResourceManager.GetString("MatchWindow_LabelHomeTeamNumberOfMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games lost:.
        /// </summary>
        public static string MatchWindow_LabelLoses {
            get {
                return ResourceManager.GetString("MatchWindow_LabelLoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games won:.
        /// </summary>
        public static string MatchWindow_LabelWins {
            get {
                return ResourceManager.GetString("MatchWindow_LabelWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Draw:.
        /// </summary>
        public static string MatchWindows_LabelDraw {
            get {
                return ResourceManager.GetString("MatchWindows_LabelDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played:.
        /// </summary>
        public static string PlayerStat_lblGamesPlayed {
            get {
                return ResourceManager.GetString("PlayerStat_lblGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        public static string PlayerStat_lblGoalsScored {
            get {
                return ResourceManager.GetString("PlayerStat_lblGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string PlayerStat_lblName {
            get {
                return ResourceManager.GetString("PlayerStat_lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: .
        /// </summary>
        public static string PlayerStat_lblPosition {
            get {
                return ResourceManager.GetString("PlayerStat_lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Cards:.
        /// </summary>
        public static string PlayerStat_lblRedCard {
            get {
                return ResourceManager.GetString("PlayerStat_lblRedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards:.
        /// </summary>
        public static string PlayerStat_lblYellowCard {
            get {
                return ResourceManager.GetString("PlayerStat_lblYellowCard", resourceCulture);
            }
        }
    }
}
